# Generated by Django 3.2.8 on 2023-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papeleria', '0002_auto_20231101_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='IVA_FACTURA',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='SALDO_FACTURA',
        ),
        migrations.AddField(
            model_name='producto',
            name='IVA_FACTURA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='IVA en la factura'),
        ),
    ]
