# Generated by Django 4.2.7 on 2023-11-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papeleria', '0004_auto_20231105_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del usuario')),
                ('usuario', models.CharField(max_length=30, verbose_name='Nombre del usuario')),
                ('contrasenia', models.CharField(max_length=30, verbose_name='Contraseña del usuario')),
            ],
        ),
    ]
