# Generated by Django 3.2.8 on 2023-11-01 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papeleria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='FECHA_PEDIDO',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha en que se realizo el pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='FECHA_PEDIDO_LLEGADA',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha en la que se espera que llegue el pedido'),
        ),
    ]
